changes

diff --git a/.github/workflows/create_terraform_json_payload.yml b/.github/workflows/create_terraform_json_payload.yml
--- a/.github/workflows/create_terraform_json_payload.yml
+++ b/.github/workflows/create_terraform_json_payload.yml
@@ -36,15 +36,22 @@ jobs:
           echo "Issue Body: ${{ github.event.issue.body }}"
 
       - name: Get issue branch name
-        id: extract_data
+        shell: bash
         run: |
           BODY="${{ github.event.issue.body }}"
-          ISSUE_BRANCH_NAME=$(echo "$BODY" | grep -oP "Please Enter the Github Feature Branch Name\s+\K\S+" || echo "No Match Found")
-          if [ "$ISSUE_BRANCH_NAME" == "No Match Found" ]; then
-            echo "Failed to extract branch name from the issue body."
-            exit 1
-          fi
+          ISSUE_BRANCH_NAME=$(echo "$BODY" | awk '/Please Enter the Github Feature Branch Name/{getline; print}')
           echo "ISSUE_BRANCH_NAME=$ISSUE_BRANCH_NAME" >> $GITHUB_ENV
+
+      # - name: Get issue branch name
+      #   id: extract_data
+      #   run: |
+      #     BODY="${{ github.event.issue.body }}"
+      #     ISSUE_BRANCH_NAME=$(echo "$BODY" | grep -oP "Please Enter the Github Feature Branch Name\s+\K\S+" || echo "No Match Found")
+      #     if [ "$ISSUE_BRANCH_NAME" == "No Match Found" ]; then
+      #       echo "Failed to extract branch name from the issue body."
+      #       exit 1
+      #     fi
+      #     echo "ISSUE_BRANCH_NAME=$ISSUE_BRANCH_NAME" >> $GITHUB_ENV
 
       - name: Print extracted issue branch name
         run: |
