changes

diff --git a/.github/workflows/create_terraform_json_payload.yml b/.github/workflows/create_terraform_json_payload.yml
--- a/.github/workflows/create_terraform_json_payload.yml
+++ b/.github/workflows/create_terraform_json_payload.yml
@@ -34,9 +34,16 @@ jobs:
 
     steps:
 
+      - name: Use the branch name
+        run: |
+          BRANCH_NAME=${{ steps.get_inputs.outputs.branch_name }}
+          echo "ISSUE_BRANCH_NAME=$ISSUE_BRANCH_NAME" >> $GITHUB_ENV
+          echo GitHub Issue Branch Name: $ISSUE_BRANCH_NAME
+
       - uses: actions/checkout@v3
         with:
           token: ${{ secrets.GH_TOKEN }}
+          ref: ${{ env.ISSUE_BRANCH_NAME }}
 
       - name: Convert Github issues title to lowercase with underscore and put in env vars
         run: |    
@@ -65,8 +72,6 @@ jobs:
           ISSUE_JSON=$(cat issue_submission/issue_submission.json)
           ISSUE_ENVIRONMENT=$(echo $ISSUE_JSON | jq -r .environment)
           echo "ISSUE_ENVIRONMENT=$ISSUE_ENVIRONMENT" >> $GITHUB_ENV
-          BRANCH_NAME=$(echo $ISSUE_JSON | jq -r .gh_branch_name)
-          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
           
 
       # - name: Fetch Terraform Json master config JSON file from the target repo
@@ -97,23 +102,18 @@ jobs:
         run: |
           echo export REF_GITHUB_URL=${{ github.server_url }}/${{ github.repository_owner }}/${{ github.event.repository.name }}.git > issue_submission/env.sh  
 
-      - uses: actions/checkout@v3
-        with:
-          token: ${{ secrets.GH_TOKEN }}
-          ref: ${{ env.gh_branch_name }}
-
       - name: Commit updated issue submission JSON file to Terraform Config repo
         run: |
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git config --global user.name "github-actions[bot]"
           git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}.git
           git fetch
-          git checkout ${{ env.gh_branch_name }} || git checkout -b ${{ env.gh_branch_name }} # Check out the branch if it exists, otherwise create it
-          git pull origin ${{ env.gh_branch_name }} || true # If the branch is new, this pull will fail, hence we use `|| true` to prevent the workflow from stopping
+          git checkout ${{ env.ISSUE_BRANCH_NAME }} || git checkout -b ${{ env.ISSUE_BRANCH_NAME }} # Check out the branch if it exists, otherwise create it
+          git pull origin ${{ env.ISSUE_BRANCH_NAME }} || true # If the branch is new, this pull will fail, hence we use `|| true` to prevent the workflow from stopping
           # Adding the entire issue_submission folder
           git add issue_submission/
           git commit -m 'new infrastructure submission' || echo "No changes to commit"
-          git push origin ${{ env.gh_branch_name }}
+          git push origin ${{ env.ISSUE_BRANCH_NAME }}
 
       # - name: Commit updated issue submission JSON file to Terraform Config repo
       #   shell: bash
