changes

diff --git a/.github/workflows/create_terraform_json_payload.yml b/.github/workflows/create_terraform_json_payload.yml
--- a/.github/workflows/create_terraform_json_payload.yml
+++ b/.github/workflows/create_terraform_json_payload.yml
@@ -100,15 +100,26 @@ jobs:
           echo export REF_GITHUB_URL=${{ github.server_url }}/${{ github.event.repository.name }} > issue_submission/env.sh  
 
       - name: Commit updated issue submission JSON file to Terraform Config repo
-        shell: bash
         run: |
-          git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
-          git config --global user.name "github-actions[bot]" && \
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git config --global user.name "github-actions[bot]"
           git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/robert-altmiller/terraform_template_config.git
           git fetch
-          git checkout bsa_feature_branch
-          git pull && \
-          git add issue_submission/ && \ # This line adds the whole folder
-          git commit -m 'new infrastructure submission' && \
-          git push
+          git checkout bsa_feature_branch || git checkout -b bsa_feature_branch # Check out the branch if it exists, otherwise create it
+          git pull origin bsa_feature_branch || true # If the branch is new, this pull will fail, hence we use `|| true` to prevent the workflow from stopping
+          # Adding the entire issue_submission folder
+          git add issue_submission/
+          git commit -m 'new infrastructure submission' || echo "No changes to commit"
+          git push origin bsa_feature_branch
+
+      # - name: Commit updated issue submission JSON file to Terraform Config repo
+      #   shell: bash
+      #   run: |
+      #     git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
+      #     git config --global user.name "github-actions[bot]" && \
+      #     git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/robert-altmiller/terraform_template_config.git
+      #     git pull && \
+      #     git add issue_submission/ && \ # This line adds the whole folder
+      #     git commit -m 'new infrastructure submission' && \
+      #     git push
   
